# Site settings
title: SJD.co
email: sam@sjd.co
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samjdavis.com" # the base hostname & protocol for your site

twitter: samjdavis
instagram: samjdavis

# Build settings
markdown: kramdown
