# Site settings
title: SJD.co
email: sam@sjd.co
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samjdavis.com" # the base hostname & protocol for your site

twitter: samjdavis
instagram: samjdavis

# Build settings
markdown: kramdown


# Application Experience:
illustrator: 100
indesign: 90
photoshop: 80
lightroom: 80
finalCut: 50
afterEffects: 40

# Language Experience:
html: 100
css: 90
javascript: 70
python: 50
objectiveC: 50
php: 40