# Site settings
title: SJD.co
email: sam@sjd.co
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samjdavis.com" # the base hostname & protocol for your site

twitter: samjdavis
instagram: samjdavis

# Build settings
markdown: kramdown

apps:
 illustrator:
  name: 'Illustrator'
  skill: 100
  icon: <i class="fa fa-pencil"></i>
 indesign:
  name: 'InDesign'
  skill: 90
  icon: <i class="fa fa-book"></i>
 photoshop:
  name: 'Photoshop'
  skill: 80
  icon: <i class="fa fa-camera"></i>
 lightroom:
  name: 'Lightroom'
  skill: 80
  icon: <i class="fa fa-lightbulb-o"></i>
 finalcut:
  name: 'Final Cut Pro X'
  skill: 50
  icon: <i class="fa fa-video-camera"></i>
 aftereffects:
  name: 'After Effects'
  skill: 40
  icon: <i class="fa fa-magic"></i>

languages:
 html:
  name: 'HTML'
  skill: 100
 css:
  name: 'CSS'
  skill: 90
 javascript:
  name: 'Javascript'
  skill: 70
 git:
  name: 'Git/Github'
  skill: 70
 sql:
  name: 'SQL'
  skill: 60
 python:
  name: 'Python'
  skill: 50
 objectiveC:
  name: 'Objective-C'
  skill: 50
 php:
  name: 'PHP'
  skill: 40

